#ifndef DEFINES_H
#define DEFINES_H

#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 240

#define VRAM_SIZE 0x4000
#define PATTERN_TABLE_SIZE 0x2000
#define SPR_RAM_SIZE 0x100
#define PALETTE_TABLE_START 0x3F00
#define PALETTE_TABLE_SPRITE_OFFSET 16

#define CPU_RAM_SIZE    2048
#define SRAM_SIZE       8192

/*** PPU CONTROL REGISTER 1 ***/
#define NAME_TABLE_X_SCROLL_MASK              0x01
#define NAME_TABLE_Y_SCROLL_MASK              0x02
#define VERTICAL_WRITE_MASK                   0x04
#define SPRITE_PATTERN_TABLE_ADDRESS_MASK     0x08
#define BACKGROUND_PATTERN_TABLE_ADDRESS_MASK 0x10
#define SPRITE_SIZE_MASK                      0x20
#define VBLANK_INTERRUPT_ENABLE_MASK          0x80

#define NAME_TABLE_X_SCROLL_BIT 0
#define NAME_TABLE_Y_SCROLL_BIT 1
#define BACKGROUND_PATTERN_TABLE_ADDRESS_BIT 4

#define VERTICAL_WRITE_ON 0x04
#define VERTICAL_WRITE_OFF 0x00

// For 8x8 sprites only
#define SPRITE_PATTERN_TABLE_ADDRESS_0000 0x00
#define SPRITE_PATTERN_TABLE_ADDRESS_1000 0x08

// compare with regS
#define REGS_BACKGROUND_PATTERN_TABLE_ADDRESS_0000 0x00
#define REGS_BACKGROUND_PATTERN_TABLE_ADDRESS_1000 0x01

#define SPRITE_SIZE_8x8 0x00
#define SPRITE_SIZE_8x16 0x20

#define VBLANK_INTERRUPT_ENABLE 0x80
#define VBLANK_INTERRUPT_DISABLE 0x00

/*** PPU CONTROL REGISTER 2 ***/
#define BACKGROUND_ENABLE_MASK 0x08
#define SPRITES_ENABLE_MASK 0x10

#define BACKGROUND_DISABLE 0x00
#define BACKGROUND_ENABLE 0x08

#define SPRITES_DISABLE 0x00
#define SPRITES_ENABLE 0x10

/*** PPU STATUS ***/
#define PPU_STATUS_MORE_THAN_8_SPRITES_HIT_MASK 0x20
#define PPU_STATUS_SPRITE_0_HIT_MASK 0x40
#define PPU_STATUS_VBLANK_MASK 0x80

#define PPU_STATUS_SPRITE_0_HIT     0x40
#define PPU_STATUS_SPRITE_0_RESET   0x00

#define PPU_STATUS_MORE_THAN_8_SPRITES_HIT 0x20
#define PPU_STATUS_MORE_THAN_8_SPRITES_RESET 0x00

#define HEADER_SIZE 16

#define PRG_ROM_BYTE 4
#define CHR_ROM_BYTE 5
#define PRG_RAM_BYTE 8

#define FOUR_SCREEN_MIRRORING 0x08
#define HORIZONTAL_MIRRORING 0x00
#define VERTICAL_MIRRORING 0x01

#define BATTERY_BACKED_SRAM 0x02
#define TRAINER 0x04

#define MAPPER_MASK 0xF0

#define PRG_ROM_PAGE_SIZE 16384 // 16kb
#define CHR_ROM_PAGE_SIZE 8192  // 8kb
#define PRG_RAM_PAGE_SIZE 8192  // 8kb



typedef enum Interrupts {
	_None,
	_NMI,
	_IRQ
};

#endif